### ISSUE TITLE
SPDXLite-Template.xlsx is not template 

### ISSUE THREAD

**Issue by fu7mu4** [OpenChain-Project/OpenChain-JWG#110]
SPDXLite-Template.xlsx in OpenChain-JWG/License-Info-Exchange/SPDX-Lite/template/ is usual excel sheet format, not template format. I think xltx is better choice. Please add xltx file instead of xlsx

 OpenChain-JWG/License-Info-Exchange/SPDX-Lite/template/SPDXLite-Template.xlsx は通常のexcelシートフォーマットでテンプレートフォーマットではありません。xltx の方がよいと思います。xlsxの代わりに xltxをアップロードしてください。

**Comment by koizumistr** [comment]
指摘ありがとうございます。 

基本的には #114 で対応していたのですが、細かい対応も #131 で終わりましたのでcloseします。
