### ISSUE TITLE
Please fix link to better URL for supplier leaflet

### ISSUE THREAD

**Issue by fu7mu4** [OpenChain-Project/OpenChain-JWG#119]
In https://openchain-project.github.io/OpenChain-JWG/outcomes.html, a link "supplier leaflet" linked to an archived repository : https://github.com/OpenChain-Project/curriculum/tree/master/supplier-leaflet . 
Where Is active materials ?

[OpenChain-JWGの成果物のページ](https://openchain-project.github.io/OpenChain-JWG/outcomes.html) の supplier leaflet のリンクですが、[アーカイブされたリポジトリ](https://github.com/OpenChain-Project/curriculum/tree/master/supplier-leaflet)へのリンクになっています。よりよい URLへのリンクに修正してほしいです。

**Comment by koizumistr** [comment]
#132 でやってみました。

が、https://www.openchainproject.org/resources の 
Get Our Supplier Education Guide にリンクを張るのが最善だという気がしないでもないです。

**Comment by fu7mu4** [comment]
私はこれでいいと思います。

**Comment by koizumistr** [comment]
確認ありがとうございます。では、closeとしますね。
