### ISSUE TITLE
"SPDX section no." in SPDXLite-Template.xltx / SPDXLite-Template.xltxの「SPDX section no.」について

### ISSUE THREAD

**Issue by yakuri** [OpenChain-Project/OpenChain-JWG#304]
The "SPDX section no." in SPDXLite-Template.xltx (red box in the screenshot below) is different from "Table G.1" in https://spdx.github.io/spdx-spec/v2.2.2/SPDX-Lite/.
Can you please correct it?

SPDXLite-Template.xltxの「SPDX section no.」（下のスクリーンショットの赤枠部分）が https://spdx.github.io/spdx-spec/v2.2.2/SPDX-Lite/ の「Table G.1」と異なっていました。
修正いただくことは可能でしょうか。

![image](https://github.com/OpenChain-Project/OpenChain-JWG/assets/62694113/ca167ac3-ce32-44f5-ac21-ea1675a70322)
![image](https://github.com/OpenChain-Project/OpenChain-JWG/assets/62694113/da8e6cd3-ff51-401c-b090-0d5d068fe8eb)

**Comment by NorioKobota** [comment]
@yakuri ご指摘ありがとうございました。
エクセルにはSPDX LiteをSPDX WGに提案した時の項目番号、つまりSPDX v2.1の時の項目番号が入っていました。
v2.2で本家の項目番号が変更となっておりエクセルとの乖離が発生していましたので修正、mergeしました。
