### ISSUE TITLE
[Question] Is SPDXLite-Template.xltx of SPDXv2.3 available? / SPDXv2.3 の SPDXLite-Template.xltx は公開されていますでしょうか

### ISSUE THREAD

**Issue by yakuri** [OpenChain-Project/OpenChain-JWG#305]
Is SPDXLite-Template.xltx of SPDXv2.3 available?

**Comment by NorioKobota** [comment]
The excel we created was for SPDX v2.1 and we have not created  it since.

**Comment by yakuri** [comment]
Thank you for your reply. I understand.
